version: 0.2

phases: 
  install: 
    commands: 
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
      - "unzip terraform_1.0.5_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - pwd
      - ls
      - cd terra
      - cd dev
      - ls
      - TF_LOG=DEBUG terraform init

  build:
    commands:
      - terraform destroy -lock=false -auto-approve

  post_build:
    commands:
      - echo "terraform apply completed on ´date´"